name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run create-change-set command
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws cloudformation create-change-set \
          --region ap-northeast-1 \
          --stack-name  ishocon2-resources \
          --change-set-name "${{ github.event.pull_request.title }}" \
          --template-body file://`pwd`/template.yml \
          --parameters file://`pwd`/parameters/production.json
