name: Execute Change Set

on:
  push:
    branches: master

jobs:
  execute:

    runs-on: ubuntu-latest

    steps:
    - name: Run execute-change-set command
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws cloudformation execute-change-set \
          --region ap-northeast-1 \
          --stack-name  ishocon2-resources \
          --change-set-name "${{ github.event.pull_request.title }}" \
